config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'root#index'
  post '/create_session', controller: :root, action: :create_session
  get '/success', controller: :root, action: :success
  get '/cancel', controller: :root, action: :cancel

  resources :accounts, only: %i[] do
    collection do
      get '/', action: :edit
      post '/', action: :edit
    end
  end
  resources :account_links, only: [] do
    collection do
      get '/', action: :start
      get 'success', action: :success
      get 'failure', action: :failures
    end
  end
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  def edit
    @account_disabled = account_disabled?

    if request.method_symbol == :get
      @individual_form = IndividualForm.new
      return
    end
    @individual_form = IndividualForm.new(edit_params)
    return render :edit unless @individual_form.validate

    # https://stripe.com/docs/connect/required-verification-information#JP-individual-card_payments
    stripe_account = Stripe::Account.update(
      current_user.stripe_account_id,
      {
        business_profile: {
          url: @individual_form.business_url
        }
      }
    )

    # 銀行口座を作成する。
    # 登録済みの銀行口座を更新することはできない。銀行口座を更新する場合、作成時と同様に `create_external_account` を叩く。
    external_account = Stripe::Account.create_external_account(
      stripe_account.id,
      external_account: {
        object: 'bank_account',
        country: 'JP',
        currency: 'jpy',
        default_for_currency: true,
        account_number: @individual_form.bank_account_number,
        routing_number: @individual_form.bank_routing_number,
        account_holder_name: @individual_form.bank_account_holder_name
      }
    )

    current_user.stripe_account_id = stripe_account.id
    current_user.external_account_id = external_account.id
    current_user.save

    store = Store.create(
      user_id: current_user.id,
      name: @individual_form.store_name,
      service_fee: @individual_form.service_fee
    )
    if stripe_account.id.present? && store.persisted?
      redirect_to root_path
    else
      render :new
    end
  rescue Stripe::InvalidRequestError => e
    logger.error e
    if e.message.start_with?('The routing number')
      @individual_form.errors.add(:invalid_bank_account, :invalid_bank_account)
    end
    render :new
  end

  def edit_params
    params.require(:individual_form).permit(
      :store_name,
      :service_fee,
      :business_url,
      :bank_number,
      :bank_branch_number,
      :bank_account_number,
      :bank_account_holder_name
    )
  end

  private

  def account_disabled?
    return true if current_user.stripe_account_id.blank?

    stripe_account = Stripe::Account.retrieve(current_user.stripe_account_id)
    # Custom Account は Account Link で External account（銀行口座・デビットカード等）の入力ができないため、
    # Account Linkの状態判定から取り除く
    disabled_reasons = stripe_account.requirements.past_due.reject { |reason| reason == 'external_account' }
    !disabled_reasons.empty?
  end
end

app/views/accounts/edit.html.erb
<h1>店舗管理</h1>

<% if @account_disabled %>
  <%= link_to '本人確認情報を入力する', account_links_path %>
  <div class="error">
    店舗登録には本人確認情報の入力が必要です
  </div>
<% else %>
  <%= link_to '本人確認情報を確認する', account_links_path %>
<% end %>

<%= form_with url: accounts_path, model: @individual_form, method: 'post', local: true do |f| %>

  <h2>店舗情報</h2>

  <fieldset>
    <legend>店舗名</legend>
    <%= f.text_field :store_name %>
    <div class="error">
      <% if @individual_form.errors.messages[:store_name].any? %>
        <%= @individual_form.errors.messages[:store_name].join('<br>').html_safe %>
      <% end %>
    </div>
  </fieldset>
  <fieldset>
    <legend>提供するサービス価格</legend>
    <%= f.text_field :service_fee, :size => 8, :maxlength => 8, placeholder: '1200' %>
    <div class="error">
      <% if @individual_form.errors.messages[:service_fee].any? %>
        <%= @individual_form.errors.messages[:service_fee].join('<br>').html_safe %>
      <% end %>
    </div>
  </fieldset>
  <fieldset>
    <legend>ホームページ</legend>
    <%= f.text_field :business_url, placeholder: 'http://example.com/' %>
    <div class="error">
      <% if @individual_form.errors.messages[:business_url].any? %>
        <%= @individual_form.errors.messages[:business_url].join('<br>').html_safe %>
      <% end %>
    </div>
  </fieldset>

  <h2>銀行口座</h2>
  <p>売上の送金先を登録します。国内の金融機関のみに対応しています。</p>
  <div class="error">
    <% if @individual_form.errors.messages[:bank_account].any? %>
      <%= @individual_form.errors.messages[:bank_account].join('<br>').html_safe %>
    <% end %>
  </div>

  <fieldset>
    <legend>銀行コード</legend>
    <%= f.text_field :bank_number, :size => 4, :maxlength => 4, placeholder: '1100' %>
    <div class="error">
      <% if @individual_form.errors.messages[:bank_number].any? %>
        <%= @individual_form.errors.messages[:bank_number].join('<br>').html_safe %>
      <% end %>
    </div>
  </fieldset>
  <fieldset>
    <legend>支店コード</legend>
    <%= f.text_field :bank_branch_number, :size => 3, :maxlength => 3, placeholder: '000' %>
    <div class="error">
      <% if @individual_form.errors.messages[:bank_branch_number].any? %>
        <%= @individual_form.errors.messages[:bank_branch_number].join('<br>').html_safe %>
      <% end %>
    </div>
  </fieldset>
  <fieldset>
    <legend>口座番号</legend>
    <%= f.text_field :bank_account_number, :size => 7, :maxlength => 7, placeholder: '0001234' %>
    <div class="error">
      <% if @individual_form.errors.messages[:bank_account_number].any? %>
        <%= @individual_form.errors.messages[:bank_account_number].join('<br>').html_safe %>
      <% end %>
    </div>
  </fieldset>
  <fieldset>
    <legend>名義</legend>
    <%= f.text_field :bank_account_holder_name, placeholder: 'カ）タロウ' %>
    <div class="error">
      <% if @individual_form.errors.messages[:bank_account_holder_name].any? %>
        <%= @individual_form.errors.messages[:bank_account_holder_name].join('<br>').html_safe %>
      <% end %>
    </div>
  </fieldset>

  <br>

  <%= f.submit '登録する' %>
<% end %>